In [8]:
import numpy as np

# sigmoid function
def nonlin(x,deriv=False):
    if(deriv==True):
        return x*(1-x)
    return 1/(1+np.exp(-x))
    
X = np.array([[0,0,1],
            [0,1,1],
            [1,0,1],
            [1,1,1]])
                
y = np.array([[0],[0],[1],[1]])

# seed random numbers to make calculation
# deterministic (just a good practice)
np.random.seed(1)

# initialize weights randomly with mean 0
syn0 = 2*np.random.random((3,1)) - 1

In [9]:
X

array([[0, 0, 1],
       [0, 1, 1],
       [1, 0, 1],
       [1, 1, 1]])

In [10]:
print(X)
print(y)
print(syn0)

[[0 0 1]
 [0 1 1]
 [1 0 1]
 [1 1 1]]
[[0]
 [0]
 [1]
 [1]]
[[-0.16595599]
 [ 0.44064899]
 [-0.99977125]]


In [11]:
nonlin(np.dot(X,syn0))

array([[ 0.2689864 ],
       [ 0.36375058],
       [ 0.23762817],
       [ 0.3262757 ]])

In [12]:
y - nonlin(np.dot(X,syn0))

array([[-0.2689864 ],
       [-0.36375058],
       [ 0.76237183],
       [ 0.6737243 ]])

In [13]:
np.dot(X.T,nonlin(nonlin(np.dot(X,syn0)),True))

array([[ 0.40098089],
       [ 0.45125596],
       [ 0.8290497 ]])

In [14]:
for iter in range(50000):

    # forward propagation
    l0 = X
    l1 = nonlin(np.dot(l0,syn0))

    # how much did we miss?
    l1_error = y - l1

    # multiply how much we missed by the 
    # slope of the sigmoid at the values in l1
    l1_delta = l1_error * nonlin(l1,True)

    # update weights
    syn0 += np.dot(l0.T,l1_delta)

print("Output After Training:")
print(l1)

Output After Training:
[[ 0.0042779 ]
 [ 0.00348742]
 [ 0.99715469]
 [ 0.99650925]]
